Repository everyone-s-garden/front_end, pull requests merged in 2024-02, with the labels that each got.

#92 styled-component provider 적용
  src/components/Header/Header.tsx
  src/index.tsx
  src/reset.css
  src/styles/styled-components.d.ts
  src/styles/theme.ts
Labels: ⚙️ Setting

#91 메인페이지 변경된 UI 적용
  src/api/WeatherAPI.ts
  src/assets/main/arrow-icon.svg
  src/assets/main/banner1.png
  src/assets/main/banner2.png
  src/assets/main/location-icon.svg
  src/assets/main/month/mobile/10월.png
  src/assets/main/month/mobile/11월.png
  src/assets/main/month/mobile/12월.png
  src/assets/main/month/mobile/1월.png
  src/assets/main/month/mobile/2월.png
  src/assets/main/month/mobile/3월.png
  src/assets/main/month/mobile/4월.png
  src/assets/main/month/mobile/5월.png
  src/assets/main/month/mobile/6월.png
  src/assets/main/month/mobile/7월.png
  src/assets/main/month/mobile/8월.png
  src/assets/main/month/mobile/9월.png
  src/assets/main/month/pc/10월.png
  src/assets/main/month/pc/11월.png
  src/assets/main/month/pc/12월.png
  src/assets/main/month/pc/1월.png
  src/assets/main/month/pc/2월.png
  src/assets/main/month/pc/3월.png
  src/assets/main/month/pc/4월.png
  src/assets/main/month/pc/5월.png
  src/assets/main/month/pc/6월.png
  src/assets/main/month/pc/7월.png
  src/assets/main/month/pc/8월.png
  src/assets/main/month/pc/9월.png
  src/assets/main/month1.png
  src/assets/main/weather/clear.svg
  src/assets/main/weather/cloud-rain.svg
  src/assets/main/weather/cloud-snow.svg
  src/assets/main/weather/cloud.svg
  src/assets/main/weather/cloudy.svg
  src/assets/main/weather/hazy.svg
  src/assets/main/weather/lightning.svg
  src/assets/main/weather/rainy.svg
  src/assets/main/weather/snow.svg
  src/assets/main/weather/wind.svg
  src/components/Spinner.tsx
  src/pages/Main/Banner.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/MonthlyCrop/MonthCropItem.tsx
  src/pages/Main/MonthlyCrop/MonthCropList.tsx
  src/pages/Main/MonthlyCrop/MonthlyCrop.tsx
  src/pages/Main/Weather/CardCurrentWeather.tsx
  src/pages/Main/Weather/CardHeader.tsx
  src/pages/Main/Weather/CardNextWeather.tsx
  src/pages/Main/Weather/TimeWeather.tsx
  src/pages/Main/Weather/Weather.tsx
  src/pages/Main/Weather/WeatherCard.tsx
  src/pages/Main/Weather/WeeklyWeather.tsx
  src/recoil/atom.ts
  src/styles/theme.ts
  src/utils/getMonthImage.ts
  src/utils/getWeatherIcon.ts
Labels: ✨ Feature, 🎨 Styling

#97 feat: MainPage 및 지도 페이지 작업
  package-lock.json
  package.json
  src/api/ChatAPI.ts
  src/api/GardenAPI.ts
  src/assets/chat/click-icon.svg
  src/assets/chat/etc-icon.svg
  src/assets/chat/plus-icon.svg
  src/assets/default_profile.png
  src/assets/main/month/pc/1월.png
  src/assets/main/month/pc/2월.png
  src/components/Header/NavLinks/MobileNavLinks.tsx
  src/components/Header/NavLinks/headerNavLinks.ts
  src/components/Header/Notification.tsx
  src/components/Header/PostOptions.tsx
  src/components/Header/UserItems.tsx
  src/components/ImageSlider.tsx
  src/hooks/useIntersectionObserver.ts
  src/index.tsx
  src/pages/Chat/Chat.tsx
  src/pages/Chat/ChatContent/BtnItems.tsx
  src/pages/Chat/ChatContent/ChatBubble.tsx
  src/pages/Chat/ChatContent/ChatContents.tsx
  src/pages/Chat/ChatContent/ContentChatList.tsx
  src/pages/Chat/ChatContent/ContentHeader.tsx
  src/pages/Chat/ChatContent/ContentInput.tsx
  src/pages/Chat/ChatContent/MobileHeader.tsx
  src/pages/Chat/ChatContent/StartContent.tsx
  src/pages/Chat/ChatList/ChatList.tsx
  src/pages/Chat/ChatList/ChatListItem.tsx
  src/pages/Main/GardenList/GardenItem.tsx
  src/pages/Main/GardenList/GardenList.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/MonthlyCrop/MonthCropList.tsx
  src/pages/Main/Weather/CardCurrentWeather.tsx
  src/pages/Main/Weather/CardNextWeather.tsx
  src/pages/Main/Weather/TimeWeather.tsx
  src/pages/Map/Map.tsx
  src/pages/Map/MapView/MyMap.tsx
  src/pages/Map/MapView/OptionBar.tsx
  src/pages/Map/MapView/SearchInput.tsx
  src/pages/ReceiveReview/ReceiveReview.tsx
  src/pages/Review/Review.tsx
  src/types/Chat.ts
  src/types/Garden.ts
  yarn.lock
Labels: ✨ Feature

#100 Feat/community
  src/api/CommunityAPI.ts
  src/components/PostList/index.tsx
  src/pages/Community/CommunityDetail/Author/index.tsx
  src/pages/Community/CommunityDetail/Comments/index.tsx
  src/pages/Community/CommunityDetail/PopularPostList/index.tsx
  src/pages/Community/CommunityDetail/PostImageSlider/index.tsx
  src/pages/Community/CommunityDetail/index.tsx
  src/pages/Community/CommunityWrite/ImageAdder/ImageSlider.tsx
  src/pages/Community/CommunityWrite/PostEditor/index.tsx
  src/pages/Community/CommunityWrite/convertToHtml.ts
  src/pages/Community/CommunityWrite/index.tsx
  src/recoil/atom.ts
Labels: ✨ Feature
